language: node_js
  node_js: 
    - lts
dist: trusty # uses trusty environment
sudo: false # when on trusty, uses Docker containers for speed
branches: 
  only: 
    - master
install: 
  - yarn --prefer-offline
cache: 
  directories: 
    - .yarn-local-mirror
email:
  on_failure: change
  on_success: never
deploy:
  provider: npm
  email:
    secure: "wHMmKNdz9bpzaGlb6cwkYzbu7zm1HlsxbfscFNLqD6Y1DFMtWumluPASGvmDg9DG2CY5/YVKU2cklZY0aNZ9pFUhsp17VFchaYnXI9y7SX7MUNXvi5DXT1Ed5Kceyov9xawkbNljJCBS0XZPA7VXNlc94F+SJ/OQJBN92eJEjlJYMnWVs9QLwiDv0EZZGXjk05DSK5wAIioP7gk/6DePTRwUR1UOpSwairlgBvGIySd+SswmDRwhXTvkDhAUdvEL0LRI2LN9QItBokQgFNt9V1V7ge2RIzhWj9AaaS2VgsUTIdoIjebISE+uQBUFHXonQ355ICj5a7U76Y4ECSvTcAL7/wOdRH4QU3nrtczUOCkhDK9YV6vhwyysusLrfc4XG32lIRQYShcxQmj3xrQlo5iAT0rtG2p51CZQ6/kMHki/b1ndkTYzC5/Uu6ON0b4Uru0T0m09PfAEwW/QMRD88Kc8HD1Slb4uF9EUPGgHNrClVF0vt+UvYoK5H53h+7YFxE0GdGDXyaA4lCwDbQ5W2tOIWbqejS4iIyPlZRfmGt0nlRp4IW0p41Xf/V+TV1m7eU2346IsEFaImy9kercpP5Kp7Y+zL+Xf6JovYVF+cZtdzOXZEYNRTypuux3Uv8M1VgYrNekhuD/NG2MXHjbs7kMOPagT3o6flvQ89SWH3Z8="
  api_key:
    secure: "TIc1RHwQKlUxaXUoHDTX6vodCZ0qRbCdlBU8Z305Ot5RV79W4g5xrTfubqf5AnA40wRbXKPLctnmHhi+ArbdFfZ4Cz6W43YdqYfeo+jmdkfvnSV5N1qTuw3YoxWGwMUKK00kBmO/z6U70aV+T8H8gwZHV0EgaAEFPxVlxHG1dP0S/7BKuzgLVQpnyLhe5Lw/DTEvFTKEnxUuTl15Ja47OJD9vitNm61MfSgkz83x1i0B9lISG9lfAf4/D+obcVNRKQCSuyWB2Z7f9BvE3hXSuR82XllPdMRsn37wKRqUJLgf3nz/fgHtuGgnpllC7sx9wT951oTXUeJC5JDcm7q0sTZIgpb15Q9muxbdJCjMVGsh7oEjOJw6lYpXYzAb2hMyIBEfT4ngrMfkPM5ThAqiFzQjotVjph7cPozFv0Kfq2Rjw4I//F48jScSuH2uC5wTXoJv8mWF9EWkzbyiGEhR92ZxT1GntLScYB3Fx4qTGA+rmuqi9RFdCFFtTYOaYvS/RB4pmRuLIJs776a/r0Xmg7LJup1KSVJhlK9PfJJt7Faqis7p0CehvZXb/xOhN8YcJIETr0AGccMobQtnBjZ5b0UySEgT1RVwXsUcxIKUKxKENlvy+3VT1MBih4Ey6M/BRDjJm+Bk+U19CWLkoJyyERShWnw3Vs71uyoEJtn643w="
  on:
    branch: master
repo: pckilgore/now-builder-terraform
